server:
  port: 2000

spring:
  application:
    #配置当前微服务名称，在Eureka注册中心，是通过微服务名称来查找调用微服务
    name: mysql-provider

  #数据源配置
  datasource:
    name: mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/crowd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

#MyBatis配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml

#日志
logging:
  level:
    com.atguigu.crowd.mapper: debug
    com.atguigu.crowd.test: debug

#eureka配置
eureka:
  client:
    service-url:
      #Eureka客户端访问Eureka服务器时使用的地址
      defaultZone: http://localhost:1000/eureka/