server:
  port: 80

spring:
  application:
    #注册到eureka的微服务名称
    name: zuul
  redis:
    #redis服务器地址
    host: 192.168.64.133
  session:
    #session存储类型
    store-type: redis

eureka:
  client:
    service-url:
      #eureka服务器地址，客户端需要往这个地址去注册
      defaultZone: http://localhost:1000/eureka
zuul:
  #不允许通过微服务名进行访问，*表示所有微服务
  ignored-services: "*"
  #在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头)
  sensitive-headers: "*"
  routes:
    #自定义路由规则
    crowd-portal:
      #将该微服务路径替换成path路径
      service-id: authentication-consumer
      #这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问
      path: /**
