server:
  port: 3000

spring:
  application:
    #配置当前微服务名称，在Eureka注册中心，是通过微服务名称来查找调用微服务
    name: redis-provider

  #redis相关配置
  redis:
    #默认使用 0 号数据库
    database: 0
    #redis服务器地址，如果redis的配置文件的 bind属性绑定了地址，需要用该地址
    host: 192.168.197.133
    #rdis默认端口6379
    port: 6379
    password: 123456
    timeout: 5000
    jedis:
      pool:
        #连接池中最大空闲连接，默认值是8
        max-idle: 500
        #连接池中的最小空闲连接，默认值是0
        min-idle: 50
        #如果赋值为 -1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhansted（耗尽）
        max-active: 1000
        #等待可用连接的最大时间，单位毫秒，默认值为 -1，表示永不超时。如果超过等待时间，则直接抛出 JedisConnectionException
        max-wait: 2000

#eureka配置
eureka:
  client:
    service-url:
      #Eureka客户端访问Eureka服务器时使用的地址
      defaultZone: http://localhost:1000/eureka/