server:
  port: 5000
spring:
  application:
    name: project-consumer
  redis:
    #redis服务器地址
    host: 192.168.64.133

  session:
    #session存储类型
    store-type: redis

  thymeleaf:
    #视图前缀
    prefix: classpath:/templates/
    #视图后缀
    suffix: .html

eureka:
  client:
    service-url:
      #eureka服务器地址，客户端需要往这个地址去注册
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI5tQ1J43vbuyuQUsFsXoM
    access-key-secret: pPTj0VnFfyVDb2towQgQmTNZJW9LnS
    bucket-domain: http://shuyun-atguigu.oss-cn-guangzhou.aliyuncs.com
    end-point: http://oss-cn-guangzhou.aliyuncs.com
    bucket-name: shuyun-atguigu