server:
  port: 4000

spring:
  application:
    #注册到eureka的微服务名称
    name: authentication-consumer
  redis:
    #redis服务器地址
    host: 192.168.64.133
  session:
    #session存储类型
    store-type: redis

  thymeleaf:
    #视图前缀
    prefix: classpath:/templates/
    #视图后缀
    suffix: .html

eureka:
  client:
    service-url:
      #eureka服务器地址，客户端需要往这个地址去注册
      defaultZone: http://localhost:1000/eureka

message:
  host: https://gyytz.market.alicloudapi.com
  path: /sms/smsSend
  method: POST
  appcode: 2fc1a2c00e5f4b22adb8571bd2b6b6ea
  smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
  templateId: 908e94ccf08b4476ba6c876d13f084ad

